[tools]
"github:docker/buildx" = "latest"
"github:docker/docker-credential-helpers" = "latest"
age = "latest"
atuin = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
biome = "latest"
bottom = "latest"
colima = "latest"
delta = "latest"
docker-cli = "latest"
docker-compose = "latest"
duckdb = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
hurl = "latest"
imagemagick = "latest"
jj = "latest"
jjui = "latest"
jq = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
minisign = "latest"
neovim = "latest"
node = "latest"
ollama = "latest"
opencode = "latest"
pandoc = "latest"
prek = "latest"
python = "latest"
restic = "latest"
ripgrep = "latest"
rumdl = "latest"
rust = "latest"
sd = "latest"
shfmt = "latest"
sops = "latest"
stylua = "latest"
tree-sitter = "latest"
typst = "latest"
uv = "latest"
yazi = "latest"
zola = "latest"
zoxide = "latest"

[settings]
legacy_version_file = false
experimental = true

[settings.python]
compile = false
uv_venv_auto = true

[settings.pipx]
uvx = true

