---
git:
  paging:
    colorArg: always
    pager: delta

customCommands:
  - key: "B"
    description: "Commitizen Tag Bump"
    context: "tags"
    loadingText: "Tagging ..."
    command: "cz bump -s --increment {{index .PromptResponses 0}}"
    prompts:
      - type: "menu"
        title: "Semver"
        options:
          - value: "PATCH"
          - value: "MINOR"
          - value: "MAJOR"
  - key: "z"
    command: "git cz c"
    description: "Commit with Commitizen no sign"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "Z"
    command: "git cz c -s"
    description: "Commit with Commitizen Signed"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "C"
    command: "cz ch"
    description: "Update/Generate Changelog"
    context: "tags"
    loadingText: "Updating Changelog"
gui:
  authorColors:
    '*': '#b4befe'
theme:
  activeBorderColor:
    - '#89b4fa'
    - bold
  inactiveBorderColor:
    - '#a6adc8'
  optionsTextColor:
    - '#89b4fa'
  selectedLineBgColor:
    - '#313244'
  cherryPickedCommitBgColor:
    - '#45475a'
  cherryPickedCommitFgColor:
    - '#89b4fa'
  unstagedChangesColor:
    - '#f38ba8'
  defaultFgColor:
    - '#cdd6f4'
  searchingActiveBorderColor:
    - '#f9e2af'
