---
git:
  paging:
    colorArg: always
    pager: delta --paging=never --hyperlinks --line-numbers

customCommands:
  - key: "B"
    description: "Commitizen Tag Bump"
    context: "tags"
    loadingText: "Tagging ..."
    command: "cz bump -s --increment {{index .PromptResponses 0}}"
    prompts:
      - type: "menu"
        title: "Semver"
        options:
          - value: "PATCH"
          - value: "MINOR"
          - value: "MAJOR"
  - key: "z"
    command: "git cz c"
    description: "Commit with Commitizen no sign"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "Z"
    command: "git cz c -s"
    description: "Commit with Commitizen Signed"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    subprocess: true
  - key: "C"
    command: "cz ch"
    description: "Update/Generate Changelog"
    context: "tags"
    loadingText: "Updating Changelog"

gui:

  spinner:
    # The frames of the spinner animation.
    frames:
      - ''
      - ''
      - ''
      - ''
      - ''
      - ''
  nerdFontsVersion: ""

  # Status panel view.
  statusPanelView: allBranchesLog
  showBottomLine: false
  authorColors:
    '*': '#c4a7e7'
  theme:
    activeBorderColor:
      - '#ebbcba'
      - bold
    inactiveBorderColor:
      - '#6e6a86'
    optionsTextColor:
      - '#908caa'
    selectedLineBgColor:
      - '#2a283e'
    selectedRangeBgColor:
      - '#56526e'
    cherryPickedCommitBgColor:
      - '#44415a'
    cherryPickedCommitFgColor:
      - '#9ccfd8'
    unstagedChangesColor:
      - '#ea9a97'
    defaultFgColor:
      - '#e0def4'
    searchingActiveBorderColor:
      - '#f6c177'
