[buildPlans.mikevka]
family = "Mikevka"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

# hintParams = ["-a", "qqq"]

[buildPlans.mikevka.ligations]
  inherits = "dlig"

[buildPlans.mikevka.metricOverride]
leading = 1100
xHeight = 550
periodSize = 'blend(weight, [425, default_periodSize * 1.2], [800, default_periodSize * 1.1])'

[buildPlans.mikevka.variants]
inherits = "ss08"

[buildPlans.mikevka.variants.design]
percent = "rings-continuous-slash"

[buildPlans.mikevka.variants.italic]
k = "cursive-serifless"
percent = "rings-continuous-slash"

[buildPlans.mikevka.widths.normal]
shape = 500
menu  = 5
css   = "normal"

[buildPlans.mikevka.weights.regular]
shape = 425
menu = 400
css = 400

[buildPlans.mikevka.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.mikevka.weights.bold]
shape = 800
menu = 700
css = 700

[buildPlans.mikevka.weights.black]
shape = 900
menu = 900
css = 900
