git:
  diffRenderers:
    - colorArg: always
      command: delta --paging=never
customCommands:
  - key: "B"
    description: "Commitizen Tag Bump"
    context: "tags"
    loadingText: "Tagging ..."
    command: "cz bump -s --increment {{index .PromptResponses 0}}"
    prompts:
      - type: "menu"
        title: "Semver"
        options:
          - value: "PATCH"
          - value: "MINOR"
          - value: "MAJOR"
  - key: "z"
    command: "git cz c"
    description: "Commit with Commitizen no sign"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    output: terminal
  - key: "Z"
    command: "git cz c -s"
    description: "Commit with Commitizen Signed"
    context: "files"
    loadingText: "Opening commitizen commit tool"
    output: terminal
  - key: "C"
    command: "cz ch"
    description: "Update/Generate Changelog"
    context: "tags"
    loadingText: "Updating Changelog"
gui:
  spinner:
    # The frames of the spinner animation.
    frames:
      - "\U0001F78C"
      - "\U0001F7B5"
      - "\U0001F7B6"
      - "\U0001F7B7"
      - "\U0001F7B8"
      - "\U0001F7B9"
      - "\U0001F7BA"
      - "\U0001F7B9"
      - "\U0001F7B8"
      - "\U0001F7B7"
      - "\U0001F7B6"
      - "\U0001F7B5"
      - "\U0001F78C"
  nerdFontsVersion: ""
  # Status panel view.
  statusPanelView: allBranchesLog
  showBottomLine: false
  theme:
    activeBorderColor:
      - "#31748f"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    searchingActiveBorderColor:
      - "#ebbcba"
      - bold
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#31748f"
    inactiveViewSelectedLineBgColor:
      - "#26233a"
      - bold
    cherryPickedCommitFgColor:
      - "#1f1d2e"
    cherryPickedCommitBgColor:
      - "#ebbcba"
    markedBaseCommitFgColor:
      - "#9ccfd8"
    markedBaseCommitBgColor:
      - "#f6c177"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
