"text"      = { fg = "#e0def4" }
"dimmed"    = { fg = "#45475a" }
"title"     = { fg = "#89b4fa", bold = true }
"shortcut"  = { fg = "#cba6f7" }
"matched"   = { fg = "#f5e0dc" }
"border"    = { fg = "#45475a" }
"selected"  = { bg = "#1f1d2e", fg = "#e0def4", bold = true }

"source_marker" = { bg = "#89dceb", fg = "#1e1e2e", bold = true }
"target_marker" = { bg = "#9ccfd8", fg = "#1e1e2e", bold = true }

"status" = { bg = "#1f1d2e" }
"status title" = { fg = "#1e1e2e", bg = "#74c7ec", bold = true }

"revset title" = { fg = "#89b4fa", bold = true }
"revset text" = { fg = "#e0def4", bold = true }
"revset completion text" = { fg = "#e0def4" }
"revset completion matched" = { fg = "#f5e0dc", bold = true }
"revset completion dimmed" = { fg = "#45475a" }
"revset completion selected" = { bg = "#1f1d2e", fg = "#e0def4" }

"revisions" = { fg = "#e0def4" }
"revisions selected" = { bg = "#1f1d2e"}
"revisions dimmed" = { fg = "#45475a" }
"revisions details selected" = { bg = "#313244" }
"oplog selected" = { bold = true }

"evolog" = { fg = "#e0def4" }
"evolog selected" = { bg = "#313244", fg = "#e0def4", bold = true }

"menu" = { bg = "#1e1e2e", fg = "#c4a7e7" }
"menu title" = { fg = "#1e1e2e", bg = "#c4a7e7", bold = true }
"menu shortcut" = { fg = "#c4a7e7" }
"menu matched" = { fg = "#f5e0dc", bold = true }
"menu dimmed" = { fg = "#45475a" }
"menu border" = { fg = "#1f1d2e" }
"menu selected" = { bg = "#313244", fg = "#e0def4" }

"help" = { bg = "#1e1e2e", fg = "#c4a7e7" }
"help title" = { fg = "#9ccfd8", bold = true, underline = true }
"help border" = { fg = "#1f1d2e" }

"preview" = { fg = "#e0def4" }
"preview border" = { fg = "#1f1d2e" }

"confirmation" = { bg = "#1e1e2e" }
"confirmation text" = { fg = "#89b4fa", bold = true }
"confirmation dimmed" = { fg = "#45475a" }
"confirmation border" = { fg = "#eb6f92", bold = true }
"confirmation selected" = { bg = "#313244", fg = "#e0def4" }

"undo" = { bg = "#1e1e2e" }
"undo confirmation dimmed" = { fg = "#45475a" }
"undo confirmation selected" = { bg = "#313244", fg = "#e0def4" }

"success" = { fg = "#9ccfd8", bold = true }
"error" = { fg = "#eb6f92", bold = true }
"revisions rebase source_marker" = { bold = true }
"revisions rebase target_marker" = { bold = true }
"status shortcut" = { fg = "#c4a7e7" }
"status dimmed" = { fg = "#45475a" }

"details" = { fg = "#e0def4" }
"details selected" = { bold = true }
"completion" = { fg = "#e0def4" }
"completion selected" = { bold = true }
"rebase" = { bold = true }

"workspace" = { fg = "#74c7ec" }
"branch" = { fg = "#89dceb" }
"commit" = { fg = "#9ccfd8" }
"file" = { fg = "#f5e0dc" }
"change" = { fg = "#eb6f92" }
"bookmark" = { fg = "#c4a7e7" }
